CREATE TABLE [dbo].[Movies]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[GenreId] UNIQUEIDENTIFIER NULL,
    [Name] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(500) NULL,
	[ReleaseDate] DATETIME2 NULL, 
    CONSTRAINT [FK_Movies_Genres] FOREIGN KEY (GenreId) REFERENCES [Genres]([Id]),
)
